#!/usr/bin/env python

# Automatically generated by nengo-bones, do not edit this file directly

import io
import pathlib
import runpy
import numpy as np

try:
    from setuptools import Extension, find_packages, setup
    from setuptools.command.build_ext import build_ext as _build_ext
except ImportError:
    raise ImportError(
        "'setuptools' is required but not installed. To install it, "
        "follow the instructions at "
        "https://pip.pypa.io/en/stable/installing/#installing-with-get-pip-py"
    )

class build_ext(_build_ext):
    def finalize_options(self):
        _build_ext.finalize_options(self)
        # Prevent numpy from thinking it is still in its setup process:
        __builtins__.__NUMPY_SETUP__ = False
        import numpy
        self.include_dirs.append(numpy.get_include())

def read(*filenames, **kwargs):
    encoding = kwargs.get("encoding", "utf-8")
    sep = kwargs.get("sep", "\n")
    buf = []
    for filename in filenames:
        with io.open(filename, encoding=encoding) as f:
            buf.append(f.read())
    return sep.join(buf)


root = pathlib.Path(__file__).parent
version = runpy.run_path(str(root / "abr_jaco2" / "version.py"))["version"]

install_req = [
    "cython>=0.29.0",
    "numpy>=1.16.0",
    "setuptools>=18.0",
    "cloudpickle>=0.8.0",
    "sympy>=1.3",
]

setup_req = [
    "numpy>=1.16.0",
]
docs_req = []
optional_req = []
tests_req = []

setup(
    name="abr-jaco2",
    version=version,
    author="Applied Brain Research",
    author_email="pawel.jaworski@appliedbrainresearch.com",
    packages=find_packages(),
    url="https://github.com/abr/abr_jaco2",
    include_package_data=False,
    license="Free for non-commercial use",
    description="Python interface for low-level force control of Kinova Jaco2",
    long_description=read("README.rst", "CHANGES.rst"),
    zip_safe=False,
    install_requires=install_req,
    extras_require={
        "all": docs_req + optional_req + tests_req,
        "docs": docs_req,
        "optional": optional_req,
        "tests": tests_req,
    },
    python_requires=">=3.6",
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Framework :: ABR Jaco2",
        "Intended Audience :: Science/Research",
        "License :: Free for non-commercial use",
        "Operating System :: Ubuntu <=16.02",
        "Programming Language :: Python :: 3 :: Only",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    cmdclass = {'build_ext': build_ext},
    ext_modules=[
        Extension(
            "abr_jaco2.interface.jaco2_rs485",
            sources=["abr_jaco2/interface/jaco2_cython.pyx",
                     "abr_jaco2/interface/jaco2_rs485.cpp"],
            language="c++",
            include_dirs=[np.get_include()],
            extra_compile_args=["-ldl"],
        )
    ]
)
